// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.1
// source: gui/io/log.proto

package io

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filenames []string `protobuf:"bytes,1,rep,name=filenames,proto3" json:"filenames,omitempty"`
	Target    string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Request   string   `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Metadata  string   `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Response  string   `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gui_io_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_gui_io_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_gui_io_log_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

func (x *Log) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Log) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *Log) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Log) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type SearchLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value      *Log   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	MethodInfo string `protobuf:"bytes,3,opt,name=method_info,json=methodInfo,proto3" json:"method_info,omitempty"`
}

func (x *SearchLog) Reset() {
	*x = SearchLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gui_io_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLog) ProtoMessage() {}

func (x *SearchLog) ProtoReflect() protoreflect.Message {
	mi := &file_gui_io_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLog.ProtoReflect.Descriptor instead.
func (*SearchLog) Descriptor() ([]byte, []int) {
	return file_gui_io_log_proto_rawDescGZIP(), []int{1}
}

func (x *SearchLog) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchLog) GetValue() *Log {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SearchLog) GetMethodInfo() string {
	if x != nil {
		return x.MethodInfo
	}
	return ""
}

var File_gui_io_log_proto protoreflect.FileDescriptor

var file_gui_io_log_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x75, 0x69, 0x2f, 0x69, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x69, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x1c,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5b, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x69, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x6f, 0x76, 0x65, 0x72, 0x4a, 0x69, 0x65, 0x2f, 0x70,
	0x74, 0x67, 0x2f, 0x67, 0x75, 0x69, 0x2f, 0x69, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_gui_io_log_proto_rawDescOnce sync.Once
	file_gui_io_log_proto_rawDescData = file_gui_io_log_proto_rawDesc
)

func file_gui_io_log_proto_rawDescGZIP() []byte {
	file_gui_io_log_proto_rawDescOnce.Do(func() {
		file_gui_io_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_gui_io_log_proto_rawDescData)
	})
	return file_gui_io_log_proto_rawDescData
}

var file_gui_io_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gui_io_log_proto_goTypes = []interface{}{
	(*Log)(nil),       // 0: io.Log
	(*SearchLog)(nil), // 1: io.SearchLog
}
var file_gui_io_log_proto_depIdxs = []int32{
	0, // 0: io.SearchLog.value:type_name -> io.Log
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gui_io_log_proto_init() }
func file_gui_io_log_proto_init() {
	if File_gui_io_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gui_io_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gui_io_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gui_io_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gui_io_log_proto_goTypes,
		DependencyIndexes: file_gui_io_log_proto_depIdxs,
		MessageInfos:      file_gui_io_log_proto_msgTypes,
	}.Build()
	File_gui_io_log_proto = out.File
	file_gui_io_log_proto_rawDesc = nil
	file_gui_io_log_proto_goTypes = nil
	file_gui_io_log_proto_depIdxs = nil
}
